//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUISAdminApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessages
    {
        public int MessageIDX { get; set; }
        public Nullable<int> MessageTypeCode { get; set; }
        public Nullable<int> BizTypeCode { get; set; }
        public string DialogName { get; set; }
        public string Message { get; set; }
        public string UserID { get; set; }
        public string SessionID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<int> TopIntentIDX { get; set; }
        public Nullable<decimal> TopIntentScore { get; set; }
        public Nullable<int> SubIntentIDX { get; set; }
        public Nullable<decimal> SubIntentScore { get; set; }
        public bool IsSuccess { get; set; }
        public Nullable<decimal> BaseScore { get; set; }
        public Nullable<System.DateTime> ReturnMessageDate { get; set; }
    }
}
